# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmsg.proto\x12\x02RL\"2\n\x07\x43ontact\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x03(\t\x12\r\n\x05\x65mail\x18\x03 \x03(\tb\x06proto3')



_CONTACT = DESCRIPTOR.message_types_by_name['Contact']
Contact = _reflection.GeneratedProtocolMessageType('Contact', (_message.Message,), {
  'DESCRIPTOR' : _CONTACT,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:RL.Contact)
  })
_sym_db.RegisterMessage(Contact)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTACT._serialized_start=17
  _CONTACT._serialized_end=67
# @@protoc_insertion_point(module_scope)
